### ISSUE TITLE
Unable to load bert.bin model

### ISSUE THREAD

**Issue by bianyueX** [mayuefine/c_AMPs-prediction#1]
Hi, thank you for your nice work at first, I am really insterested  in your NLP models which with high precision of prediction.
I am trying to use your model to predict AMPs , there are some problems when I using bert model to do prediction for a test.

Before running the command, I used conda to create the environment with the requirements:
numpy=1.18.1
pandas=1.0.2
scikit-learn=0.22.1
tensorflow=1.14.0
Python=3.6
bert-sklearn was  downloaded from github (https://github.com/charles9n/bert-sklearn), but only found 0.3.0 release.
then I downloaded `bert.bin` from the URL that you provided.

the command is runing on a server with GPU. I got this erro (the server is not mine, so some private information has been hided):
![2790150f437aee0ab7ffdbdcd5dd687](https://user-images.githubusercontent.com/101706286/158578455-6d1f017d-699d-47aa-8438-e67f381be9b9.jpg)

It seems that there is problem with the bert model  `bert.bin`, some parameters may lost?
I hope you can help me to solve this problem.Thanks!

**Comment by mayuefine** [comment]
I have uploaded the [bert_sklearn](https://github.com/mayuefine/c_AMPs-prediction/tree/master/bert_sklearn), and tested it on another computer that had not run this project. As shown in the picture, the program works fine~
![test](https://user-images.githubusercontent.com/20675866/158928404-eeb4ec7a-7e87-4708-9e7d-38cb2eb0d11a.png)
.

**Comment by bianyueX** [comment]
It worked finally! Thank you very much~
