### ISSUE TITLE
Questions about the output results of the BERT model

### ISSUE THREAD

**Issue by RChGO** [mayuefine/c_AMPs-prediction#13]
Hello Dr. Ma,

After running the BERT model, I obtained a series of numbers (as shown below). I noticed that the minimum value for all sequences in this model is consistently above 0.5, and the majority of the values are exactly 0.7932512. I find this somewhat peculiar and am unsure if my results are correct. The output results from the other two models appear much more normal, with a range of values from high to low.

####The output results of the BERT model
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.83117896
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.8630788
0.7932512
0.6921963
0.7932512
0.7932512
0.7932512
0.7140603
0.7932512
0.79557246
0.81547713
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7343733
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.7932512
0.8213214
0.7932512
...

**Comment by yaqinZhong** [comment]
Hello, may I ask if you have solved the current problem? I found that all the prediction results I got after running the program were 0.7932512. I tried reinstalling the program and many other methods but none of them solved the problem.

**Comment by RChGO** [comment]
You might have made the same mistake as I did, accidentally using the output file from format.pl as the input file for prediction_bert.py. The input file for prediction_bert.py is different from that of the first two models; it should be a _**FASTA**_ file.

**Comment by yaqinZhong** [comment]
Thank you very much! I have been troubled by this problem for almost two weeks
