### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by lihaicheng7003** [mayuefine/c_AMPs-prediction#2]
你好，setup.py文件中，pytorch-pretrained-bert==0.6.1后面少了一个逗号

**Comment by mayuefine** [comment]
好的，谢谢提醒

**Comment by lihaicheng7003** [comment]
很有意思的工作，


在2022年3月18日 ***@***.***> 写道：

好的，谢谢提醒

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
